### ISSUE TITLE
Unable to find "snowpack-template-preset-en" in the npm registry.

### ISSUE THREAD

**Issue by markfirmware** [argyleink/snowpack-template-preset-env#5]
npx create-snowpack-app --template snowpack-template-preset-en abc
    npx: installed 29 in 11.172s

    [ERROR] Unable to find "snowpack-template-preset-en" in the npm registry.
    [ERROR] Cannot continue safely. Exiting...

**Comment by argyleink** [comment]
`npx create-snowpack-app --template snowpack-template-preset-env abc`

`preset-en` -> `preset-env` 👍
